import streamlit as st
from PIL import Image
image = Image.open('helpmodel.png')

def app():
    st.title('Help Page!')
    st.header('Explanation of the variables:')
    st.caption('Mean --> Is the arithmetic average of a finite set of numbers. In the case of a gaussian distribution, it is the central point that the distributions tend towards.')
    st.caption('Standard Deviation (std) --> Is the amount of variation that a finite set of numbers have from the mean. In the case of a gaussian distribution, a low std value means that the values tend to be closer to the mean, while a high value means that the values are further away from the mean.')
    st.caption('Walk-In Arrivals --> The inter-arrival time for Walk-In patients. It is how long (in minutes) the system must wait before generating a new patient. In other words, after a patient arrives how much do you need to wait before a new patient arrives.')
    st.caption('Ambulance Arrivals --> The inter-arrival time for Ambulance patients. It is how long (in minutes) the system must wait before generating a new patient. In other words, after a patient arrives how much do you need to wait before a new patient arrives.')
    st.caption('Priority Assessment --> When a patient arrives at the hospital a nurse will evaluate the patient and check to see if the patient needs priority. The mean is the average time that a nurse takes to assess a patient. The std is how much it will deviate from the mean.')
    st.caption('CTAS Assessment --> A nurse will evaluate the patient and give it a CTAS level. The mean is the average time that a nurse takes to assess a patient. The std is how much it will deviate from the mean.')
    st.caption('Registration --> A nurse will register a patient in the department. The mean is the average time that the nurse and patient take to complete the registration. The std is how much it will deviate from the mean.')
    st.caption('Bed Assignment --> A nurse will take the patient to the bed and, if needed, the nurse will take and prepare any equipment. The mean is the average time that a nurse takes to prepare the bed, equipment and, take the patient to the bed. The std is how much it will deviate from the mean.')
    st.caption('Resuscitation --> A patient with CTAS level 1 will go to the resuscitation bed and will be treated by a doctor and a nurse until the patient is recovered. The mean is the average time that it takes a patient to be stabilized. The std is how much it will deviate from the mean.')
    st.caption('Initial Assessment --> A nurse will do the initial assessment of the patient. The mean is the average time that a nurse takes to do the initial interview with the patient. The std is how much it will deviate from the mean.')
    st.caption('Treatment --> A nurse and a doctor will treat the patient. The mean is the average time that a doctor takes to do the treatment of the patient. The std is how much it will deviate from the mean.')
    st.caption('Discharge Decision --> The patient will be discharged from the ED department. The mean is the average time that it takes to discharge a patient. The std is how much it will deviate from the mean.')
    st.caption('CTAS Distribution --> The chance (in percentage) of a patient having a certain CTAS level. The sum of CTAS levels 1 to 5 must be 100.')
    st.header('Explanation of the model:')
    st.image(image) 
    st.caption('Patient flow through the emergency department.')
    st.caption('A patient can arrive at the emergency department by walking or by ambulance.')
    st.caption('If a patient arrives by ambulance it means that the paramedics already performed the Priority Assessment so, an ambulance patient will skip the ER Priority Assessment. Otherwise, all patients will undergo Priority Assessment. The Priority Assessment is carried out by a nurse.')
    st.caption('If a patient is CTAS level 1, they will undergo resuscitation procedures. From Priority Assessment or ambulance they will go to Resuscitation where they will be given a special resuscitation bed, a nurse and a doctor. From there the doctor and the nurse will treat and stabilize the patient. After the patient is stabilized, the patient will be discharged from the ER department.')
    st.caption('If a patient is CTAS level 2, they will go from the ambulance or Priority Assessment to the Bed Assignment.')
    st.caption('After the ambulance or Priority Assessment, CTAS levels 3, 4 and 5 will go to the CTAS Assessment where a nurse will do a more detailed investigation and determine their risks and what kind of help they need.')
    st.caption('From CTAS Assessment the patients will go to Registration where a nurse will register them into the ER department. Following the Registration the patients will go to Bed Assignment where a nurse will put the patient in an available bed.')
    st.caption('Then a nurse will perform the Initial Assessment of the patient and after a doctor and a nurse will perform the Treatment of the patient.')
    st.caption('Finally, the patient is sent to discharge where the patient will free the bed and be discharged from the ER department.')
